name: gamewallpaper
description: A new Flutter application.
version: 1.0.0+0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.1.0
  flutter_cache_manager: ^1.4.1
  oktoast: ^2.3.2
  flutter_downloader: ^1.4.4
  path_provider: ^1.5.1
  permission_handler: ^4.0.0
  cupertino_icons: ^0.1.2
  flutter_easyloading: ^1.1.4
  webview_flutter: ^0.3.22+1
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  encrypt: ^4.0.0
  cached_network_image: ^2.2.0+1
  facebook_app_events: ^0.6.0
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

